clc
clear

%V1.0 by Manu 
% this code goes into all the files generated by the code
% "tracking_MSD_batch_dataset" and compile the results in a nice 
% excel file by Field Of View (FOV).
% run in at the root folder (where "tracking_MSD_batch_dataset" is)

%Output: DperFOW matrix
%1 sample name (aka folder name)
%2 FOV number (aka number of Tif file)
%3 total number of tracks in this FOV
%4 number of tracks passing the selection
%5 mean diffusion coefficient in the FOV
%6 sem of diffusion coefficient in the FOV

r2threhold=0.9; %threshold in r² to keep the tracks
alphathrehold=0.45; %threshold in alpha bellow which to remove tracks for Deff

nbinDeff=50; %nbins for Deff distrib
Deffmax=0.5;   %Deff max for Deff distrib in um²/s
binDeff=0:Deffmax/nbinDeff:Deffmax;
binDeff2=0:Deffmax/nbinDeff:(Deffmax-Deffmax/nbinDeff);
binDeff2=binDeff2';

%do FOW per FOW
DperFOW=cell(1,7);
q=1;
DperFOW{q,1}='sample';
DperFOW{q,2}='FOV number';
DperFOW{q,3}='total number of tracks in this FOV';
DperFOW{q,4}='number of tracks passing the selection';
DperFOW{q,5}='median diffusion coefficient in the FOV';
DperFOW{q,6}='sem of diffusion coefficient in the FOV';


q=q+1;

cd raw;
fol=dir;
sfol=size(fol,1);

for p=3:sfol
    clc
    display(cat(2,'processing folder ',num2str(p-2),' of ',num2str(sfol-2)));
     cd(fol(p).name);
     load('Pool__tracksNMSD.mat');
     
     %number of FOV in this sample
     
     ncell=size(Pool_MSDfit,1);
     for j=1:ncell
         Temp=Pool_MSDfit{j,1};
     
        b=find(Temp(:,8)>r2threhold);
        sub=Temp(b,:);
        b=find(sub(:,6)>alphathrehold);
        sub=sub(b,:);
    DperFOW{q,5}=median(sub(:,4));
    DperFOW{q,6}=std(sub(:,4))/sqrt(length(sub(:,4)));
    DperFOW{q,4}=length(sub(:,4));
    DperFOW{q,3}=length(Temp(:,4));
    DperFOW{q,2}=cat(2,'cell #',num2str(j));
    DperFOW{q,1}=fol(p).name;
    
    q=q+1;
         
     end
     cd ..
end    
cd ..
xlswrite('medianMSDperFOV.xls',DperFOW);